// index.js — Rulebook Portal API server (READ-ONLY).
//
// Boot sequence: wait for the ephemeral Postgres -> read the rulebook ->
// generically seed EVERY table it defines into a scratch `portal` schema ->
// serve read-only browse endpoints. There is no write surface: the rulebook,
// skills/, and rulespeak/ are the only durable state; this DB is a disposable
// projection rebuilt fresh on every `docker compose up --build`.

import express from 'express';
import {
  waitForDb,
  seedFromRulebook,
  listTableSummaries,
  getTableRows,
  getRow,
  integrity,
  driftSummary,
} from './db.js';
import { readRulebook, readRulespeak, listTables } from './rulebook.js';

const app = express();

// Log a one-line trace per API call.
app.use((req, _res, next) => {
  if (req.path.startsWith('/api')) console.log(`  ${req.method} ${req.path}`);
  next();
});

app.get('/api/health', async (_req, res) => {
  res.json({ ok: true, readOnly: true });
});

// Top-level summary: rulebook name/description, tables (name, description,
// field count, row count), and global integrity/drift summary counts.
app.get('/api/state', async (_req, res, next) => {
  try {
    const rb = readRulebook();
    const [tables, issues, drift] = await Promise.all([
      listTableSummaries(),
      integrity(),
      driftSummary(),
    ]);
    const descByName = Object.fromEntries(listTables(rb).map((t) => [t.name, t.description]));
    res.json({
      readOnly: true,
      rulebookName: rb.Name,
      rulebookDescription: rb.Description,
      tables: tables.map((t) => ({ ...t, description: descByName[t.name] || '' })),
      integrity: { count: issues.length, issues },
      drift: {
        count: drift.length,
        driftedCount: drift.filter((d) => d.drifted).length,
      },
    });
  } catch (e) {
    next(e);
  }
});

// Schema + all rows for a table, relationship fields resolved to labels.
app.get('/api/tables/:tableName', async (req, res, next) => {
  try {
    const result = await getTableRows(req.params.tableName);
    if (!result) return res.status(404).json({ ok: false, error: `no such table: ${req.params.tableName}` });
    res.json({ table: req.params.tableName, ...result });
  } catch (e) {
    next(e);
  }
});

// Single row detail, keyed by the calculated `Name` field.
app.get('/api/tables/:tableName/rows/:rowName', async (req, res, next) => {
  try {
    const result = await getRow(req.params.tableName, req.params.rowName);
    if (!result) return res.status(404).json({ ok: false, error: 'not found' });
    res.json({ table: req.params.tableName, ...result });
  } catch (e) {
    next(e);
  }
});

// Raw rulespeak.md content, as generated by rulebook-to-rulespeak.
app.get('/api/rulespeak', (_req, res, next) => {
  try {
    res.type('text/plain').send(readRulespeak());
  } catch (e) {
    next(e);
  }
});

// Dedicated drift view: SkillBodies snapshot vs live SKILL.md on disk.
app.get('/api/drift', async (_req, res, next) => {
  try {
    const drift = await driftSummary();
    res.json(
      drift.map((d) => ({
        skill: d.name,
        path: d.path,
        drifted: d.drifted,
        drift_reason: d.drift_reason,
      })),
    );
  } catch (e) {
    next(e);
  }
});

app.use((err, _req, res, _next) => {
  console.error('API error:', err);
  res.status(500).json({ ok: false, error: String(err.message || err) });
});

const PORT = Number(process.env.PORT || 5177);

(async () => {
  console.log('Rulebook Portal API (read-only) starting…');
  console.log('  waiting for ephemeral Postgres…');
  await waitForDb();
  console.log('  seeding scratch DB generically from effortless-rulebook.json…');
  const rb = readRulebook();
  await seedFromRulebook(rb);
  const tables = await listTableSummaries();
  console.log('  seeded tables:');
  for (const t of tables) console.log(`    ${t.name}: ${t.fields} fields, ${t.rows} rows`);
  app.listen(PORT, () => console.log(`  API listening on http://0.0.0.0:${PORT}`));
})().catch((e) => {
  console.error('FATAL boot error:', e);
  process.exit(1);
});
